### ISSUE TITLE
Limit on Passwords

### ISSUE THREAD

**Issue by borecchio** [spob/Firehoze#2]
There doesn’t seem to be a limit on how large your account password can be.  Is this intended or a bug? 
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
This is my password for a test account with username, test

For the last name and first name sections when creating an account, an error occurs when you go past 40 letters and I was wondering if it should be like this for the password.

**Comment by spob** [comment]
Can you be more specific on your wording? For example, you say "For the last name and first name sections when creating an account, an error occurs". Are you saying that you get a stack trace, or do you get a nice user warning telling you you've exceeded the maximum length.

**Comment by spob** [comment]
If I'm understanding this issue, I don't think there is a bug here. Unless you see some behavior not working -- e.g., getting an unexpected error message or long passwords not authenticating properly, I don't think there's a problem here. Am I misreading this?
