### ISSUE TITLE
Can't see my video

### ISSUE THREAD

**Issue by borecchio** [spob/Firehoze#5]
I created a lesson and can not see it at the home page or access it.  
1. I wrote in my title and description
2. put in the path for a test mpeg-4 video.  
3. went to home page to see it and it is not there

Maybe that functionality has not been added yet for the author to see his videos? 
Or maybe only Bob can create a lesson right now that shows up in the home page?

**Comment by spob** [comment]
When you upload a lesson, it triggers a background process to convert the video to flash and upload the converted video to Amazon S3. Depending on the size of the video, that can take between several seconds and several minutes. Once the video is finished, the lesson will be marked as ready and will show up in all searches. Until that point, the lesson will be hidden (unless you are a sysadmin).

There is a bug here...the author shoudl be able to view their video, even if it's not ready. I'll fix that.

Note that video playback is not yet coded either.

**Comment by borecchio** [comment]
okay cool.  I didn't even realize that my videos were going to show up eventually.  This site is coming along awesome!
